apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llmo-cert
spec:
  dnsNames:
  - api.llmo.cloudnatix.com
  secretName: llmo-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
