apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kenji@cloudnatix.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: kong
    - selector:
        dnsZones:
        - "llmo.cloudnatix.com"
      dns01:
        route53:
          region: us-west-2
          hostedZoneID: Z0433180WK0MXJ89V9Y5 # llmo.cloudnatix.com
          role: arn:aws:iam::803339316953:role/LLMOperatorDevCertManagerMonitoring
