global:
  llmOperatorBaseUrl: https://api.llmo.cloudnatix.com/v1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/response-buffering: "false"
    tls:
      hosts:
      - api.llmo.cloudnatix.com
      secretName: api-tls

  auth:
    oidcIssuerUrl: https://api.llmo.cloudnatix.com/v1/dex

  workerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc

  workerServiceIngress:
    create: true
    ingressClassName: kong
    annotations:
      konghq.com/protocols: grpc,grpcs

dex-server:
  oauth2:
    passwordConnector:
      enable: false
    responseTypes:
    - code
  connectors:
  - type: oidc
    id: okta
    name: okta
    config:
      # Using the "Internal" Okta API authorization server
      issuer: https://login.cloudnatix.com/oauth2/aus24366mbRFxF3De4x7
      clientID: 0oak1yta82395U5wP4x7
      clientSecret: nxU6XRatwKdweHn-CgS5YiYKNfahfS8l1N3kjhqNeWfPEAEb7ub2TfvezU5OYifH
      redirectURI: https://api.llmo.cloudnatix.com/v1/dex/callback
      insecureSkipEmailVerified: true
      scopes:
      - profile
      - email
      - offline_access

  enablePasswordDb: false
  staticPassword:
    enable: false
  staticClient:
    enable: true
    clients:
    - id: llm-operator
      name: LLM Operator
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
      redirectURIs:
      - http://127.0.0.1:5555/callback
    - id: session-manager
      name: LLM Operator
      secret: o15FQlUB8SeOOBiw3Pg5vD5p
      redirectURIs:
      - https://api.llmo.cloudnatix.com/v1/sessions/callback
  # Have the same configuration as Okta
  expiry:
   idTokens: 1h
   refreshTokens:
     validIfNotUsedFor: 168h

inference-manager-server:
  workerServiceTls:
    enable: true
    secretName: llmo-cert
  workerServiceGrpcService:
    type: NodePort
    nodePort: 31235

session-manager-server:
  auth:
    resolverAddr: ""
  tls:
    enable: true
    secretName: llmo-cert
  workerServiceHttpService:
    type: NodePort
    nodePort: 31234


vector-store-manager-server:
  llmEngineAddr: ollama.ollama:8080
