apiVersion: v1
kind: Namespace
metadata:
  name: ollama

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: OLLAMA_HOST
          value: 0.0.0.0:8080

---

apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
  - port: 8080
    name: http
    targetPort: http
    protocol: TCP
