apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kenji@cloudnatix.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: kong
    - selector:
        dnsZones:
        - "dev.llmo.cloudnatix.com"
      dns01:
        route53:
          region: us-west-2
          hostedZoneID: Z088868619GNGWXDWWMEJ # dev.llmo.cloudnatix.com
          role: arn:aws:iam::803339316953:role/LLMOperatorDevCertManagerMonitoring
