tracking:
  extraEnvVars:
  - name: MLFLOW_DEPLOYMENTS_TARGET
    value: http://deployment-server:7000
  - name: MLFLOW_S3_ENDPOINT_URL
    value: http://minio.minio:9000

postgresql:
  enabled: false

externalDatabase:
  host: postgres.postgres.svc.cluster.local
  port: 5432
  user: ps_user
  database: mlflow
  authDatabase: mlflow_auth
  existingSecret: postgres
  existingSecretPasswordKey: password

minio:
  enabled: false

externalS3:
  host: minio.minio
  port:	9000
  useCredentialsInSecret: true
  existingSecret: aws
  existingSecretAccessKeyIDKey: accessKeyId
  existingSecretKeySecretKey: secretAccessKey
  protocol: http
  bucket: mlflow
  serveArtifacts: true
