apiVersion: v2
name: llm-operator
description: A Helm chart for LLM Operator
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: cluster-manager-server
  version: 0.18.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: dex-server
  version: 0.101.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: file-manager-server
  version: 0.59.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: inference-manager-engine
  version: 0.342.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: inference-manager-server
  version: 0.342.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: job-manager-dispatcher
  version: 0.196.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: job-manager-server
  version: 0.196.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: model-manager-loader
  version: 0.102.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: model-manager-server
  version: 0.102.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: rbac-server
  version: 0.101.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: session-manager-agent
  version: 0.60.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: session-manager-server
  version: 0.60.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: user-manager-server
  version: 0.82.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: vector-store-manager-server
  version: 0.41.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
