apiVersion: v2
name: llm-operator
description: A Helm chart for LLM Operator
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: dex-server
  version: 0.21.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: file-manager-server
  version: 0.22.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: inference-manager-engine
  version: 0.42.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: inference-manager-server
  version: 0.42.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: job-manager-dispatcher
  version: 0.71.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: job-manager-server
  version: 0.71.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: model-manager-loader
  version: 0.37.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: model-manager-server
  version: 0.37.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: rbac-server
  version: 0.21.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
- name: user-manager-server
  version: 0.4.0
  repository: "http://llm-operator-charts.s3-website-us-west-2.amazonaws.com"
