apiVersion: v2
name: llm-operator
description: A Helm chart for LLM Operator
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: cluster-manager-server
  version: 0.15.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: dex-server
  version: 0.91.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: file-manager-server
  version: 0.57.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: inference-manager-engine
  version: 0.270.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: inference-manager-server
  version: 0.270.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: job-manager-dispatcher
  version: 0.188.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: job-manager-server
  version: 0.188.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: model-manager-loader
  version: 0.91.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: model-manager-server
  version: 0.91.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: rbac-server
  version: 0.91.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: session-manager-agent
  version: 0.50.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - worker
- name: session-manager-server
  version: 0.50.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: user-manager-server
  version: 0.78.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
- name: vector-store-manager-server
  version: 0.37.0
  repository: "oci://public.ecr.aws/cloudnatix/llm-operator-charts"
  tags:
  - control-plane
