global:
  auth:
    enable: true
    # This default value works if rbac-server runs in the same namespace.
    rbacInternalServerAddr: rbac-server-internal-grpc:8082

# To avoid adding a release name prefix
cluster-manager-server:
  fullnameOverride: cluster-manager-server

dex-server:
  fullnameOverride: dex-server

file-manager-server:
  fullnameOverride: file-manager-server

inference-manager-engine:
  fullnameOverride: inference-manager-engine

inference-manager-server:
  fullnameOverride: inference-manager-server

job-manager-dispatcher:
  fullnameOverride: job-manager-dispatcher

job-manager-server:
  fullnameOverride: job-manager-server

model-manager-loader:
  fullnameOverride: model-manager-loader

model-manager-server:
  fullnameOverride: model-manager-server

rbac-server:
  fullnameOverride: rbac-server

session-manager-agent:
  fullnameOverride: session-manager-agent

session-manager-server:
  fullnameOverride: session-manager-server

user-manager-server:
  fullnameOverride: user-manager-server

vector-store-manager-server:
  fullnameOverride: vector-store-manager-server
