apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      containers:
      - name: inference-server
        image: inference-server:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        # To avoid pulling the image instead of what is loaded in Kind
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: inference-server
