modelManagerServerAddr: model-manager-server-grpc.llm-operator.svc.cluster.local:8081
modelManagerInternalServerAddr: model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082

objectStore:
  s3:
    endpointUrl: http://minio.minio.svc.cluster.local:9000
    bucket: llm-operator

awsSecret:
  name: aws
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey

ingress:
  ingressClassName: kong

image:
  repository: llm-operator/inference-manager-engine
  pullPolicy: Never

version: latest
