apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-manager-server
  labels:
    app: job-manager-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-manager-server
  template:
    metadata:
      labels:
        app: job-manager-server
    spec:
      containers:
      - name: job-manager-serfver
        image: job-manager-server:latest
        # To avoid pulling the image instead of what is loaded in Kind
        imagePullPolicy: Never
        args:
        - run
        - --config
        - /etc/config/config.yaml
        ports:
        - name: grpc
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: job-manager-server
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: job-manager-server
  labels:
    app: job-manager-server
data:
  config.yaml: |-
    grpcPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: job-manager-server
  labels:
    app: job-manager-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: job-manager-server
