fileManagerServerAddr: file-manager-server-grpc.file-manager.svc.cluster.local:8081

database:
  host: postgres.postgres.svc.cluster.local
  username: ps_user

databaseSecret:
  name: postgres
  key: password

ingress:
  ingressClassName: kong

image:
  repository: llm-operator/job-manager-server
  pullPolicy: Never

version: latest
