jobNamespace: job-manager
modelManagerServerAddr: model-manager-server-internal-grpc.model-manager.svc.cluster.local:8082

modelStore:
  enable: true
  pvClaimName: model-store-volume-claim

objectStore:
  s3:
    endpointUrl: http://minio.minio.svc.cluster.local:9000
    bucket: llm-operator

awsSecret:
  name: aws
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey

database:
  host: postgres.postgres.svc.cluster.local
  username: ps_user

databaseSecret:
  name: postgres
  key: password

debug:
  # Change this to false when creating a real fine-tuning jobs.
  useFakeJob: true
