jobNamespace: llm-operator-jobs
modelManagerInternalServerAddr: model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082
fileManagerInternalServerAddr: file-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082

objectStore:
  s3:
    endpointUrl: http://minio.minio.svc.cluster.local:9000
    bucket: llm-operator

awsSecret:
  name: aws
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey

database:
  host: postgres.postgres.svc.cluster.local
  username: ps_user

databaseSecret:
  name: postgres
  key: password

debug:
  useFakeJob: false

image:
  repository: llm-operator/job-manager-dispatcher
  pullPolicy: Never

version: latest
