# Helm values for multi-cluster deployment.

global:
  workerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc

  workerServiceIngress:
    create: true
    ingressClassName: kong
    annotations:
      konghq.com/protocols: grpc,grpcs

inference-manager-engine:
  jobManagerServerWorkerServiceAddr: kong-proxy.kong:80

job-manager-dispatcher:
  fileManagerServerWorkerServiceAddr: kong-proxy.kong:80
  jobManagerServerWorkerServiceAddr: kong-proxy.kong:80
  modelManagerServerWorkerServiceAddr: kong-proxy.kong:80

model-manager-loader:
  modelManagerServerWorkerServiceAddr: kong-proxy.kong:80

session-manager-agent:
  proxy:
    baseUrl: http://kong-proxy.kong:80
