# Only install a quantalized model.
model-manager-loader:
  baseModels:
  - google/gemma-2b-it-q4

# Use a fake job.
job-manager-dispatcher:
  job:
    image: public.ecr.aws/cloudnatix/llm-operator/fake-job
    version: latest
    imagePullPolicy: IfNotPresent