# This values file is for a dev env where kong, minio, and postgres are installed in the same k8s cluster.

global:
  database:
    host: postgres.postgres.svc.cluster.local
    port: 5432
    username: ps_user
    passwordEnvName: DB_PASSWORD
    ssl:
      mode: disable

  databaseSecret:
    name: postgres
    key: password

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      region: dummy
      bucket: llm-operator

  ingress:
    ingressClassName: kong

  auth:
    # TODO(kenji): Enable once we have updated all testing script to support it (e.g., installation of rbac-manager).
    enable: false
    oidcIssuerUrl: http://kong-kong-proxy.kong/dex
    oidcClientID: llm-operator
    rbacServerAddr: http://llm-operator-rbac-server-internal-grpc:8082

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey


model-manager-loader:
  baseModels:
  - google/gemma-2b-it-q4
