# This values file is for a dev env where kong, minio, and postgres are installed in the same k8s cluster.

global:
  database:
    host: postgres.postgres.svc.cluster.local
    port: 5432
    username: ps_user
    passwordEnvName: DB_PASSWORD

  databaseSecret:
    name: postgres
    key: password

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      bucket: llm-operator

  ingress:
    ingressClassName: kong

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey


inference-manager-engine:
  modelManagerServerAddr: llm-operator-model-manager-server-grpc.llm-operator.svc.cluster.local:8081
  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082

  baseModels:
  - "gemma:2b"

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      bucket: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey

  ingress:
    ingressClassName: kong


job-manager-dispatcher:
  jobNamespace: llm-operator-jobs
  job:
    version: latest

  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082
  fileManagerInternalServerAddr: llm-operator-file-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      bucket: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey

  database:
    host: postgres.postgres.svc.cluster.local
    username: ps_user

  databaseSecret:
    name: postgres
    key: password


job-manager-server:
  jobNamespace: llm-operator-jobs

  fileManagerServerAddr: llm-operator-file-manager-server-grpc.llm-operator.svc.cluster.local:8081
  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082

  database:
    host: postgres.postgres.svc.cluster.local
    username: ps_user

  databaseSecret:
    name: postgres
    key: password

  ingress:
    ingressClassName: kong


model-manager-loader:
  baseModels:
  - google/gemma-2b

  database:
    host: postgres.postgres.svc.cluster.local
    username: ps_user

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      region: dummy
      bucket: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey

  databaseSecret:
    name: postgres
    key: password


model-manager-server:
  database:
    host: postgres.postgres.svc.cluster.local
    username: ps_user

  databaseSecret:
    name: postgres
    key: password

  ingress:
    ingressClassName: kong
