# This values file is for a dev env where kong, minio, and postgres are installed in the same k8s cluster.

global:
  database:
    host: postgres.postgres.svc.cluster.local
    port: 5432
    username: ps_user
    ssl:
      mode: disable

  databaseSecret:
    name: postgres
    key: password

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      region: dummy
      bucket: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey

  ingress:
    ingressClassName: kong

  auth:
    enable: true
    oidcIssuerUrl: http://kong-kong-proxy.kong/v1/dex
    rbacInternalServerAddr: llm-operator-rbac-server-internal-grpc:8082


model-manager-loader:
  baseModels:
  - google/gemma-2b-it-q4
