# Helm values for multi-cluster deployment.

global:
  workerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc

  workerServiceIngress:
    create: true
    ingressClassName: kong
    annotations:
      konghq.com/protocols: grpc,grpcs

inference-manager-engine:
  jobManagerServerWorkerServiceAddr: kong-proxy.kong:80
  modelManagerServerWorkerServiceAddr: kong-proxy.kong:80

job-manager-dispatcher:
  clusterManagerServerWorkerServiceAddr: kong-proxy.kong:80
  fileManagerServerWorkerServiceAddr: kong-proxy.kong:80
  jobManagerServerWorkerServiceAddr: kong-proxy.kong:80
  modelManagerServerWorkerServiceAddr: kong-proxy.kong:80

model-manager-loader:
  modelManagerServerWorkerServiceAddr: kong-proxy.kong:80

# TODO(kenji): Fix this. We cannot currently make the agent connect
# to the server via Kong since Kong does route a CONNECT request
# to a backend. Instead Kong returns a method-not-alowed error.
session-manager-agent:
  proxy:
    baseUrl: http://session-manager-server-worker-service-http.llm-operator:8082
