# This values file is for a dev env where kong, minio, and postgres are installed in the same k8s cluster.

global:
  database:
    host: postgres.postgres.svc.cluster.local
    port: 5432
    username: ps_user
    passwordEnvName: DB_PASSWORD

  databaseSecret:
    name: postgres
    key: password

  objectStore:
    s3:
      endpointUrl: http://minio.minio.svc.cluster.local:9000
      region: dummy
      bucket: llm-operator

  ingress:
    ingressClassName: kong

  auth:
    enable: true
    oidcIssuerUrl: http://kong-kong-proxy.kong/dex
    oidcClientID: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey


inference-manager-engine:
  baseModels:
  - google/gemma-2b

  modelManagerServerAddr: llm-operator-model-manager-server-grpc.llm-operator.svc.cluster.local:8081
  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082


job-manager-dispatcher:
  jobNamespace: llm-operator-jobs
  job:
    version: latest

  fileManagerInternalServerAddr: llm-operator-file-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082
  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082


job-manager-server:
  jobNamespace: llm-operator-jobs

  fileManagerServerAddr: llm-operator-file-manager-server-grpc.llm-operator.svc.cluster.local:8081
  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082


model-manager-loader:
  baseModels:
  - google/gemma-2b

  modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc.llm-operator.svc.cluster.local:8082
