baseModels:
- google/gemma-2b

database:
  host: postgres.postgres.svc.cluster.local
  username: ps_user

objectStore:
  s3:
    endpointUrl: http://minio.minio.svc.cluster.local:9000
    bucket: llm-operator

awsSecret:
  name: aws
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey

huggingFaceSecret:
  name: hugging-face
  apiKeyKey: apiKey

databaseSecret:
  name: postgres
  key: password

image:
  repository: llm-operator/model-manager-loader
  pullPolicy: Never

version: latest
