apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-store-volume
  labels:
    type: local
    app: model-store
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/model-store

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store-volume-claim
  namespace: job-manager
  labels:
    app: model-store
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-store-volume-inference
  labels:
    type: local
    app: model-store
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/model-store
