baseModels:
- google/gemma-2b

database:
  host: postgres.postgres.svc.cluster.local
  username: ps_user

objectStore:
  s3:
    endpointUrl: http://minio.minio.svc.cluster.local:9000
    region: dummy
    bucket: llm-operator

awsSecret:
  name: aws
  accessKeyIdKey: accessKeyId
  secretAccessKeyKey: secretAccessKey

databaseSecret:
  name: postgres
  key: password
