apiVersion: v1
kind: Service
metadata:
  name: inference-manager-service-nodeport
  namespace: llm-operator
spec:
  type: NodePort
  ports:
  - name: ws-grpc
    port: 8082
    protocol: TCP
    targetPort: ws-grpc
    nodePort: 31235
  selector:
    app.kubernetes.io/instance: llm-operator
    app.kubernetes.io/name: inference-manager-server
