global:
  worker:
    registrationKeySecret:
      name: cluster-registration-key
      key: regKey

  objectStore:
    s3:
      endpointUrl: http://minio:9000

inference-manager-engine:
  inferenceManagerServerWorkerServiceAddr: control-plane:82
  modelManagerServerWorkerServiceAddr: control-plane:80

job-manager-dispatcher:
  clusterManagerServerWorkerServiceAddr: control-plane:80
  fileManagerServerWorkerServiceAddr: control-plane:80
  jobManagerServerWorkerServiceAddr: control-plane:80
  modelManagerServerWorkerServiceAddr: control-plane:80

model-manager-loader:
  modelManagerServerWorkerServiceAddr: control-plane:80

session-manager-agent:
  proxy:
    baseUrl: http://control-plane:81
