apiVersion: v1
kind: Service
metadata:
  name: session-manager-service-nodeport
  namespace: llmariner
spec:
  type: NodePort
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: ws-http
    nodePort: 31234
  selector:
    app.kubernetes.io/instance: llmariner
    app.kubernetes.io/name: session-manager-server
