name: CI-post-merge
on:
  push:
    branches:
    - main

permissions:
  # This is necessary for AWS credentials. See:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write

jobs:

  update-tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llmariners
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - name: Set up Helm
      uses: Azure/setup-helm@v4
    - name: build and push helm chart
      run: |
        helm dependency build ./deployments/llm-operator
        helm package --version ${{ needs.update-tag.outputs.new_version }} ./deployments/llm-operator
        helm push llm-operator-${{ needs.update-tag.outputs.new_version }}.tgz oci://public.ecr.aws/cloudnatix/llm-operator-charts
