name: CI-pre-merge
on:
  pull_request:
    branches:
    - main

jobs:

  validate-helm-dependency:
    name: build helm dependency
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm
      uses: Azure/setup-helm@v4
    - name: Validate helm dependencies
      run: |
        helm dependency build ./deployments/llmariner
