name: CI-post-merge
on:
  push:
    branches:
    - main

permissions:
  # This is necessary for AWS credentials. See:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write

jobs:

  re-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Re-test
      run: make test

  update-tag:
    runs-on: ubuntu-latest
    needs:
    - re-test
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

  publish-binary:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    strategy:
      matrix:
        os:
        - linux
        - darwin
        - windows
        arch:
        - amd64
        - arm64
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Build binary
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        FLAG_CLI_VERSION="-X github.com/llmariner/llmariner/cli/internal/version.gitTag=${{ needs.update-tag.outputs.new_version }}"; \
        FLAG_CLI_SHA="-X github.com/llmariner/llmariner/cli/internal/version.gitCommitSha=$(git rev-parse --short HEAD)"; \
        make build BUILD_FLAGS="-ldflags \"$FLAG_CLI_VERSION $FLAG_CLI_SHA\""
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llmariners
        aws-region: us-west-2
    - name: Publish binary
      run: aws s3 cp ./bin/llma s3://llmariner-artifacts/artifacts/cli/${{ needs.update-tag.outputs.new_version }}/${{ matrix.os }}-${{ matrix.arch }}/llma

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llmariners
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - name: Set up Helm
      uses: Azure/setup-helm@v4
    - name: build and push helm chart
      run: |
        helm dependency build ./deployments/llmariner
        helm package --version ${{ needs.update-tag.outputs.new_version }} ./deployments/llmariner
        helm push llmariner-${{ needs.update-tag.outputs.new_version }}.tgz oci://public.ecr.aws/cloudnatix/llmariner-charts
